name:                pokedex
version:             0.1.0.0
synopsis:            Command line program that takes a Pokémon's name as input and returns some information about that Pokémon as the output
category:            Game
github:              neilshaabi/pokedex
license:             BSD3
author:              Neil Shaabi
maintainer:          neil.shaabi@warwick.ac.uk
copyright:           2022 Neil Shaabi
description:         Please see the README on GitHub at <https://github.com/neilshaabi/pokedex#readme>
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- text
- wreq
- http-client
- lens
- aeson

library:
  source-dirs: src

executables:
  pokedex-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pokedex